---
version: "3.3"

services:
  db:
    stdin_open: true
    tty: true
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - dockerfiles/db/conf.env
  api:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dockerfiles/dev/Dockerfile
    env_file:
      - dockerfiles/dev/conf.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - "5000"
    command: >
      bash -c "
        sleep 5s
        python carstore3000/api.py
      "


volumes:
  db_data:
    driver: local
